apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubervise

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: kubervise
  app.kubernetes.io/managed-by: kustomize
